image: alvrme/alpine-android:android-34-jdk17

variables:
  IXOPAY_GATEWAY_HOST: "injected by runner"
  IXOPAY_TOKENIZATION_HOST: "injected by runner"
  IXOPAY_INTEGRATION_KEY: "injected by runner"

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

build:
    stage: build
    only:
        - branches
    script:
        - ./gradlew --build-cache :ixopay-tokenization-demoapp:assemble :publishToMavenLocal
        - ./gradlew --build-cache test -Dcom.ixopay.gateway_host="$IXOPAY_GATEWAY_HOST" -Dcom.ixopay.tokenization_host="$IXOPAY_TOKENIZATION_HOST" -Dcom.ixopay.integration_key="$IXOPAY_INTEGRATION_KEY"
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: push
        paths:
            - build
            - .gradle
